radir/urls.py
# This file is part of radir.
#
# radir is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# radir is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General
# Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with radir.  If not, see
# <http://www.gnu.org/licenses/>.

"""radir URL Configuration"""
from django.db.models import Count
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from radir.jsonapi import router
from radir.station import (StationCreateView, StationDetailView,
                           StationUpdateView, StationListView,
                           CountryListView, LanguageListView, TagListView,
                           StreamCreateView, StreamView, StreamUpdateView)
from radir.views import (RootView,LicenseView, UserProfileRedirectView,
                         UserCreateView, UserUpdateView)

urlpatterns = [
    # Admin and Account urls:
    url(r'^admin/', include(admin.site.urls)),
    url('^accounts/', include('django.contrib.auth.urls')),
    url('^accounts/register/$', UserCreateView.as_view(), name="register"),
    url('^accounts/profile/$', login_required(
        UserProfileRedirectView.as_view()), name="user_profile"),
    #url('^accounts/id/(?P<pk>[\d]+)$', UserUpdateView.as_view(),
    #    name="user_profile"),
    url(r'^$', RootView.as_view(), name="root"),
    url(r'^licenses/$', LicenseView.as_view(), name="licenses"),
    url(r'^country/$', CountryListView.as_view(),
        name='country-listing'),

    url(r'^language/$', LanguageListView.as_view(),
        name='language-listing'),
    url(r'^language/(?P<language>[\w-]+)/$', StationListView.as_view(),
        name='station-by-language'),

    url(r'^tag/$', TagListView.as_view(),
        name='tag-listing'),
    url(r'^tag/(?P<tag>[\w-]+)$', StationListView.as_view(),
        name='station-by-tag'),

    # Station Views
    url(r'^station/$', StationListView.as_view(),
        name='station-listing'),
    url(r'^country/(?P<country>[\w --,.]+)$', StationListView.as_view(),
        name='station-by-country'),
    url(r'^station/(?P<pk>[\d]+)/$', StationDetailView.as_view(),
        name='station-home'),
    url(r'^station/add/$', StationCreateView.as_view(),
        name='station-create'),
    url(r'^station/(?P<pk>[\d]+)/edit/$', StationUpdateView.as_view(),
        name='station-edit'),

    # Stream Views
    # Request a specific stream format, e.g. OGG
    url(r'^station/(?P<station>[\d]+)/stream/format/((?P<format>[\w-]+)/)?$',
        StreamView.as_view(),
        name='stream-format'),
    url(r'^station/(?P<station>[\d]+)/stream/add/$', StreamCreateView.as_view(),
        name='stream-create'),
    url(r'^station/(?P<station>[\d]+)/stream/(?P<pk>[\d]+)/edit/$',
        StreamUpdateView.as_view(),
        name='stream-edit'),
    # Load the "default" stream (aka the first in our list?!)
    url(r'^station/(?P<station>[\d]+)/stream/$',
        StreamView.as_view(),
        name='stream-home'),
    # Load a specific stream
    url(r'^station/(?P<station>[\d]+)/stream/(?P<pk>[\d]+)/$',
        StreamView.as_view(),
        name='stream-home'),

    url(r'^api/v1/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

radir/models.py
# This file is part of radir.
#
# radir is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# radir is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General
# Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with radir.  If not, see
# <http://www.gnu.org/licenses/>.

from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify

class Country(models.Model):
    name = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Language(models.Model):
    name = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class StreamFormat(models.Model):
    name = models.CharField(max_length=40, unique=True)
    extension = models.CharField(max_length=3, unique=True)
    description = models.TextField(blank=True,null=True)

    def __str__(self):
        return self.name


class Stream(models.Model):
    url = models.URLField(null=True, blank=True, unique=True,
                          help_text="URL of the media stream.")
    format = models.ForeignKey(StreamFormat, on_delete=models.SET_NULL,
                               blank=True,
                               null=True,)
    bitrate = models.PositiveIntegerField(null=True, blank=True,
                  help_text="""Bitrate of the media stream (leave empty if """
                            """unknown).""")
    station = models.ForeignKey("Station", related_name='streams',
                                on_delete=models.CASCADE)
    last_checked = models.DateField(null=True, blank=True, default=None)

    def get_absolute_url(self):
        return reverse('stream-home', args=[self.station.pk, self.pk])

    def __str__(self):
        """Construct a nice string representation for our stream"""
        #TODO: Perhaps caching this string would be opportune for perf reasons.
        s = ""
        if self.format: s = str(self.format)
        if self.bitrate: s+= "-{}".format(self.bitrate)
        if s is not "":
            s += " ({})".format(self.station.slug)
            return s
        else: return self.station.slug

class Station(models.Model):
    name = models.CharField(max_length=40, unique=True,
               help_text="""Proper name of the radio station""")
    slug = models.SlugField(editable=True, unique=True)
    date_added = models.DateField(auto_now_add=True)
    likes = models.PositiveIntegerField(default=0)
    logo = models.ImageField(null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL,
                                blank=True,
                                null=True,
        help_text="""Select the Country the station is in.""")
    language = models.ForeignKey(Language, on_delete=models.SET_NULL,
                                 blank=True,
                                 null=True,)
    tags = models.ManyToManyField(Tag, blank=True)
    website = models.URLField(null=True, blank=True,
                              help_text="Website of the radio station")
    #"stream_set" is reverse defined on a Stream.

    def save(self, *args, **kwargs):
        if not self.id or not self.slug:
            # Newly created object or no slug value, so set it
            self.slug = slugify(self.name)
        super(Station, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('station-home', args=[self.pk])

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

radir/views.py
# This file is part of radir.
#
# radir is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# radir is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General
# Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with radir.  If not, see
# <http://www.gnu.org/licenses/>.

from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db.models import Count
from django.views.generic import TemplateView, RedirectView, UpdateView
from django.views.generic.edit import CreateView
from radir.models import Station, Country, Language, Tag

class RootView(TemplateView):
    template_name = "root.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(RootView, self).get_context_data(
            **kwargs)
        # Add in summary statistics for the homepage
        context['num_countries'] = Country.objects.annotate(
            Count('station')).filter(station__count__gt=0).count()
        context['num_languages'] = Language.objects.annotate(
            Count('station')).filter(station__count__gt=0).count()
        context['num_tags'] = Tag.objects.annotate(
            Count('station')).filter(station__count__gt=0).count()
        context['num_stations'] = Station.objects.count()
        return context


class LicenseView(TemplateView):
    template_name = "licenses.html"

class UserProfileRedirectView(UpdateView):
    """Show the user's profile page"""
    model = User
    #form_class = UserChangeForm
    fields = ['first_name','last_name','email']
    def get_success_url(self): return reverse('user_profile')

    def get_object(self, queryset=None):
        return self.request.user

class UserCreateView(CreateView):
    #TODO: Log the user automatically in after creating her
    template_name='registration/register.html'
    form_class=UserCreationForm,
    success_url='/accounts/profile/'

class UserUpdateView(UpdateView):
    model = User
    form_class = UserChangeForm
    exclude = ['password']
    #    fields = ['__all__']

radir/templates/radir/country_list.html
{% extends "base.html" %}
{% block breadcrumb %}{{block.super}} ▶ <a href="{%url 'country-listing'%}">Countries</a>{% endblock breadcrumb %}
{% block content %}
<h1>List of countries</h1>
<ul>
  {% for country in country_list %}
  <li><a href="{% url 'station-by-country' country %}">{{ country.name }}</a> ({{country.station_set.count}})</li>
  {% endfor %}
</ul>
{% endblock %}

radir/templates/radir/language_list.html
{% extends "base.html" %}
{% block breadcrumb %}{{block.super}} ▶ <a href="{%url 'language-listing'%}">Languages</a>{% endblock breadcrumb %}
{% block content %}
<h1>List of Languages</h1>
<ul>
  {% for lang in language_list %}
  <li><a href="{% url 'station-by-language' lang %}">{{ lang.name }}</a> ({{lang.station_set.count}})</li>
  {% endfor %}
</ul>
{% endblock %}

radir/templates/radir/station_detail.html
{% extends "base.html" %}
{% block breadcrumb %}{{block.super}} ▶ <a href="{%url 'station-listing'%}">Stations</a> ▶ <a href="{% url 'station-home' station.pk %}">{{station}}</a>{% endblock breadcrumb %}
{% block content %}
<h1 style="display: inline-block;">{{station}}</h1>

<section><h2 style="display: inline-block;">Streams</h2>
  <span class="button"><a href="{% url 'stream-create' station.pk %}">Add stream <img src="/static/radir/img/add.svg" width="20px" height="20px"/></a></a></span>
  {%if station.streams.count %}<span class="button"><a href="{% url 'stream-home' station.pk %}">Play a stream <img src="/static/radir/img/play.svg" width="20px" height="20px"/></a></span>{%endif%}
<table>{% for stream in station.streams.all %}
  <tr><th style="text-align:right;">{{stream}}</th>
    <td><a href="{% url 'stream-home' station.pk stream.pk %}"><img src="/static/radir/img/play.svg" width="20px" height="20px"/></a>
    <a href="{% url 'stream-edit' station.pk stream.pk %}"><img src="/static/radir/img/edit.svg" width="20px" height="20px"/></a></td></tr>{% endfor %}
</table></section>

<h2 style="display: inline-block;">Metadata of '{{station.name}}'</h2>
<span class="button"><a href="{% url 'station-edit' station.pk %}">Edit <img src="/static/radir/img/edit.svg" width="20px" height="20px"/></a></span>
<table>

  <tr><th style="text-align:right;">Short webname:</th><td>{{station.slug}}</td></tr>
  <tr><th style="text-align:right;">Likes:</td><td>{{station.likes}}</td></tr>
  <tr><th style="text-align:right;">Logo:</td><td>{{station.logo}}</td></tr>
  <tr><th style="text-align:right;">Website:</td><td>{{station.website}}</td></tr>
  <tr><th style="text-align:right;">Country:</td><td><a href="{% url 'station-by-country' station.country %}">{{station.country}}</a></td></tr>
  <tr><th style="text-align:right;">Language:</td><td><a href="{% url 'station-by-language' station.language %}">{{station.language}}</a></td></tr>
<tr><th style="text-align:right;">Tags:</td><td>{% for tag in station.tags.all %}<a href="{% url 'station-by-tag' tag %}">{{tag}}</a> {% endfor %}</td></tr>
  <tr><th style="text-align:right;">Added on:</th><td style="text-align:right;">{{station.date_added}}</td></tr>
</table>
{% endblock %}

radir/templates/radir/station_form.html
{% extends "base.html" %}
{% block breadcrumb %}{{block.super}} ▶ <a href="{%url 'station-listing'%}">Stations</a> ▶ {% if station %}<a href="{% url 'station-edit' station.pk %}">{{station}}{% else %}<a href="{% url 'station-create' %}">Add{% endif %}</a>{% endblock breadcrumb %}

{% block content %}<h1>Station '{{station}}'</h1>
<form action="" method="post">{% csrf_token %}
  <table>
  {{ form }}
</table>
  <input type="submit" value="Save" /> After saving, you will have an opportunity to add a stream URL.
</form>
{% endblock %}

radir/templates/radir/station_list.html
{% extends "base.html" %}
{% block breadcrumb %}{{block.super}} ▶ <a href="{%url 'station-listing'%}">Stations</a>{% endblock breadcrumb %}
{% block content %}
<h1>Radio stations</h1>
{% include "radir/station_table_snippet.html"%}
{% endblock %}

radir/templates/radir/station_list_countries.html
{% extends "base.html" %}
{% block breadcrumb %}{{block.super}} ▶ <a href="{%url 'country-listing'%}">Countries</a>  ▶  <a href="{%url 'station-by-country' country.name %}">{{country}}</a>{% endblock breadcrumb %}
{% block content %}
<h1>Radio stations in {{country}}</h1>
{% include "radir/station_table_snippet.html"%}
{% endblock %}

radir/templates/radir/station_list_lang.html
{% extends "base.html" %}
{% block breadcrumb %}{{block.super}} ▶ <a href="{%url 'language-listing'%}">Languages</a>  ▶  <a href="{%url 'station-by-language' language %}">{{language}}</a>{% endblock breadcrumb %}
{% block content %}
<h1>Radio stations in {{language}}</h1>
{% include "radir/station_table_snippet.html"%}
{% endblock %}

radir/templates/radir/station_list_tag.html
{% extends "base.html" %}
{% block breadcrumb %}{{block.super}} ▶ <a href="{%url 'tag-listing'%}">Tags</a>  ▶  <a href="{%url 'station-by-tag' tag %}">{{tag}}</a>{% endblock breadcrumb %}
{% block content %}
<h1>Radio stations with tag "{{tag}}"</h1>
{% include "radir/station_table_snippet.html"%}
{% endblock %}

radir/templates/radir/station_table_snippet.html
<p>Showing stations {{page_obj.start_index}}-{{page_obj.end_index}} out of {{paginator.count}} (page {{page_obj.number}} of {{paginator.num_pages}}). {% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}">&lt;previous page</a>{% endif %} 
{% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}">next page&gt;</a>{% endif %}</p>
<table id="station_table">
  {% for station in station_list %}
  <tr class="{% cycle 'row_odd' 'row_even' %}"><td width="10%"><b><a href="{% url 'station-home' station.pk %}">{{ station.name }}</a></b></td><td width="10%">{% for tag in station.tags.all %}<a href="{% url 'station-by-tag' tag %}">{{tag}}</a> {% endfor %}</td><td width="80%"><span class="button"><a href="{% url 'stream-home' station.pk %}">Play <img src="/static/radir/img/play.svg" width="20px" height="20px"/></a></span></td></tr>
  {% endfor %}
</table>

<span class="button"><a href="{% url 'station-create' %}">Add station <img src="/static/radir/img/add.svg" width="20px" height="20px"/></a></span>

radir/templates/radir/stream_detail.html
{{stream.url}}

radir/templates/radir/stream_form.html
{% extends "base.html" %}
{% block breadcrumb %}{{block.super}} ▶ <a href="{%url 'station-listing'%}">Stations</a> ▶ <a href="{% url 'station-home' station.pk %}">{{station}}</a>  ▶  {% if stream %} Stream {% else %}<a href="{% url 'stream-create' station.pk %}">Add</a>{% endif %}{% endblock breadcrumb %}

{% block content %}<h1>{% if stream %}Edit{% else %}Add{% endif %} stream for station '{{station}}'</h1>
<form action="" method="post">{% csrf_token %}
  <table>
  {{ form }}
</table>
  <input type="submit" value="Save" />
</form>
{% endblock %}

radir/templates/radir/tag_list.html
{% extends "base.html" %}
{% block breadcrumb %}{{block.super}} ▶ <a href="{%url 'tag-listing'%}">Tags</a>{% endblock breadcrumb %}
{% block content %}
<h1>List of Tags</h1>
<ul>
  {% for tag in tag_list %}
  <li><a href="{% url 'station-by-tag' tag %}">{{ tag }}</a> ({{tag.station_set.count}})</li>
  {% endfor %}
</ul>
{% endblock %}